### ISSUE TITLE
Example reduced spectra

### ISSUE THREAD

**Issue by zonca** [oirlab/iris_visualization#1]
@nils-erik do we have an example reduced spectra that I can publish publicly to test visualization?

It would be nice to have something smallish with something interesting to look at.

**Comment by zonca** [comment]
@nils-erik @arunsurya77 do we have an example reduced spectra that I can publish publicly to test visualization?

It would be nice to have something smallish with something interesting to look at.

**Comment by zonca** [comment]
@nils-erik @arunsurya77 do we have an example reduced spectra that I can publish publicly to test visualization?

It would be nice to have something smallish with something interesting to look at.

**Comment by arunsurya77** [comment]
Hi Nils ,
Do you have a simulated spectral cube for some science case that can be
used for this. I think that will be ideal for visualization testing.
Cheers
Arun

**Comment by nils-erik** [comment]
Here's a sky-subtracted cube of S06 at the GC. This one is just a single spectrum and source, so it's pretty straightforward.  Let me know if a slightly more complex one would be useful.
https://drive.google.com/file/d/19y5UeKlle3cUR3JDTq-n1VXiLaEulM6r/view?usp=sharing

**Comment by zonca** [comment]
@nils-erik thanks, yes, if you already have a more complicated one I would use both, if not, no need to produce it for me yet.

**Comment by nils-erik** [comment]
Okay, here's a slightly more complex one of a host galaxy with several lensed quasars around it.
https://drive.google.com/file/d/1A71eD58K4uDkbCMnaUw_brLMtbXEs2Uy/view?usp=sharing

**Comment by zonca** [comment]
@nils-erik I am now getting "Access denied" on the more complex example, can you please fix permissions?

**Comment by nils-erik** [comment]
Should be fixed.

**Comment by zonca** [comment]
very good thanks, I posted them to figshare for later reference https://figshare.com/account/projects/69722/articles/13718131

**Comment by zonca** [comment]
@nils-erik to make it to load in `jdaviz`, I had to add some metadata about WCS and units:

```
CTYPE3  = 'WAVE-LOG'           /                                                
CRPIX3  =                    1 / Starting pixel (1-indexed)                     
CRVAL3  =        3621.59598486 / Central wavelength of first pixel              
CD3_3   =       0.833903304339 / Initial dispersion per pixel                   
CUNIT3  = 'Angstrom'           /                                                
CRPIX1  =              38.0000 /Reference pixel (1-indexed)                     
CRPIX2  =              38.0000 /Reference pixel (1-indexed)                     
CRVAL1  =        205.438400000 /                                                
CRVAL2  =        27.0047540000 /                                                
CD1_1   =         -0.000138889 /                                                
CD2_2   =          0.000138889 /                                                
CTYPE1  = 'RA---TAN'           /                                                
CTYPE2  = 'DEC--TAN'           /                                                
CUNIT1  = 'deg     '           /                                                
CUNIT2  = 'deg     '           /                                                
```

however this metadata come from a completely different file, do you have reasonable values for your file (https://drive.google.com/file/d/1A71eD58K4uDkbCMnaUw_brLMtbXEs2Uy/view?usp=sharing)? Doesn't need to be exact, just reasonable enough for testing purposes.

**Comment by nils-erik** [comment]
Cube with metadata here:
https://drive.google.com/file/d/1n1qCXUf4JOuj18g1Y5I21WXM2w4ajPRE/view?usp=sharing

**Comment by zonca** [comment]
@nils-erik to make it work I had to apply this fix:

    f[1].header["CTYPE3"] = 'DEC--TAN' 

you had `DEC---TAN` instead.
now I am not sure about the conventions but could it be wrong?

**Comment by zonca** [comment]
also, in the previous file I was seeing some sources:

See https://github.com/oirlab/iris_visualization/blob/93005b9fe34d73b32c8ca62118be423dcb12eb89/img/jdaviz_example.jpg

while here I just see lines:

![image](https://user-images.githubusercontent.com/383090/108569790-5c6f8880-72c1-11eb-96ca-d6cd3c56d1e9.png)

is it possible that I am confusing the axis?

**Comment by nils-erik** [comment]
@zonca the sources are there, it looks like a difference in what axes you select for the spatial and spectral visualizations. 
Do you know if jdaviz uses a specific axes standard?
Is it possible to change them around or is it required to be in [x, y, lambda] or [lambda, x, y]?

**Comment by zonca** [comment]
can you tell me what is the shape of the different axes so I can verify I am reading it right? i.e. what is the length of the X, Y and lambda axis.

**Comment by nils-erik** [comment]
The shape of the cube should be in [x, y, lambda] (given by the NAXIS1, NAXIS2, and NAXIS3 keywords) and is 45 x 88 x 1598.

**Comment by zonca** [comment]
ok, so it seems like your file has wrong headers:

```
NAXIS1  =                   45 / Number of positions along axis 1               
NAXIS2  =                   88 / Number of positions along axis 2               
NAXIS3  =                 1598 / Number of positions along axis 3               
CTYPE1  = 'WAVE    '           /                                                
CTYPE2  = 'RA---TAN'           /                                                
CTYPE3  = 'DEC---TAN'          /                                                
CUNIT1  = 'nm      '           /                                                
CUNIT2  = 'deg     '           /                                                
CUNIT3  = 'deg     '           /                                                
```

For now I'll hack around this by swapping `CTYPE1` and `CTYPE3`, same with `CUNIT`

**Comment by zonca** [comment]
ok, after this fix, it loads fine into `jdaviz`:

![image](https://user-images.githubusercontent.com/383090/111524270-72823480-8719-11eb-812d-045209c065d3.png)

**Comment by zonca** [comment]
ok, I've published the file on Figshare and updated instructions on how to load it:

https://github.com/oirlab/iris_visualization
